# This is the main configuration file for the MkDocs website.
# Use hash-comments to comment out pages have not been written
# Reference: http://www.mkdocs.org/user-guide/configuration/
#
site_name: Learn / Google Cloud Platform
# For now the documentation is minimal and provides useful information for OWF.
nav:
- Home: index.md
- Introduction: introduction.md
  #- Getting Started: getting-started.md
  # - GCP Accounts and IAM: accounts-iam.md
  # - GCP Console & Dashboard: console-dashboard.md
  # - Storage: storage.md
  # - Virtual Machines: vm.md
  # - Websites: website.md
- Analytics: analytics/analytics.md
- Command Line Interface: cli/cli.md
  # - Examples for Common Tasks: common-tasks.md
  # - GCP Best Practices: best-practices.md
  # - Troubleshooting: troubleshooting/troubleshooting.md
- Resources: resources.md
# ------- configuration properties ---------------
copyright:  Copyright Open Water Foundation
# Use extra CSS to customize styles, based on theme.
extra_css:
  - 'css/extra-material-theme.css'
# ------------------------------------------------
# Google Analytics
# - see:  https://squidfunk.github.io/mkdocs-material/getting-started/#google-analytics
extra:
  analytics:
    provider: google
    property: 'G-KJFMBY739T'
# Use Material theme
# - installation notes:  https://github.com/squidfunk/mkdocs-material
theme: material
# Don't show the repo because distracting edit icons are shown and the GitHub icon takes up space
#repo_url:  https://github.com/OpenWaterFoundation/owf-learn-ckan
site_description:  Open Water Foundation Learn GCP
site_author:  Open Water Foundation
# Use Material theme
# - installation notes:  https://github.com/squidfunk/mkdocs-material
theme:
  name: material
  favicon:  'images/OWF-Logo-Favicon-32x32.png'
